status:
  port: "16241"

routes:
   - input:
      plugin: http
      config:
         port: 22132
     channel:
      output:
         plugin: yc_logs
         config:
            loggroup_id: "e23hejkb6fh8r3jnsobv"
            iam:
               cloud_meta: {}

import:
- /etc/yandex/unified_agent/conf.d/*.yml
